language: ruby
rvm:
- 2.0.0
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: rk2wljCqWUD7kx4wfUQZHbCo5EW3rv/fS4xhMK03mcMxs0e6SQf6+tmyC+YsxwBlkFDsxSlzFkRPFDnOqkBfDwkih5+fiFG3Rm4Omu7YnqK/vn9SupB/rdZcKbtdB+1YRwCQiFek9r1SC/OjrtddNDk4c3keXzdCxIVK5Xp+GRw=
  app: glacial-coast-3420
  run: rake db:migrate
  on:
    repo: deiga/ratebeer
env:
  global:
  - secure: Tzkk4/hhDvjjIYShu/9/nDmursBI/lXjMSXsZQ4I/8x/q9w1HLJb0Wq3GFeGlz7c5m6Vfvai1nHC9i14rs9XpIPbbbdXs7KOUdbhK19IHVcGo+Le0DaeCMewTzfsZ7YRj2m9bRxuBxGURG1M/EvalugRfEyj7sAPoUEAZVhGLhE=
  - secure: RZBAmPYvJl+qSGsTSXdlCW0DQP0D8ur9yK3g+fi0VIBk5icDS92SxfCImBUoK62VeuIgegI+xUW9O8XsAozVrPvIg/K+regYFdvglqv4M/fzEQuqbthzzEXKHNDAIOlaKjddjgas/q+yUqLZ7VAbnnjRuk8fWv8cT7eZBwbZKwg=
  - secure: pR8NoSy0KaMbkeXzU+r9NJa6F1JlRvABFYqPTKXzhsR8J0n8P4M54HhuKKr0SNT1BF8qGVF1iIwcETgPl/fGPOrfZLGKdAjC2hw8tVHglil5RVE/vL5+iHFzgy/ymGd2YudG9s014d9J6BaL1pjrJQUjHmlSp7F8GXD2HxzUqBE=
  - secure: YKBggtQAKKeEUYvnkp+Fqb1L+IrUrPVAl8svj0R2+F/rp1uUohqCqffaNul6hMR8rujLDcJeBjq4X3bnGtczJU+hbFQoSgJvG4OfcAJZXZmmVyCRHpPtm7omLlhN9udjz0b4Jt0JTaclysKvLOiRuIB4xhlAE5IXVLtQRHSMlOA=
