language: ruby
rvm:
- 2.0.0
before_script:
- export SECRET_KEY_BASE=$(rake secret)
script:
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: rk2wljCqWUD7kx4wfUQZHbCo5EW3rv/fS4xhMK03mcMxs0e6SQf6+tmyC+YsxwBlkFDsxSlzFkRPFDnOqkBfDwkih5+fiFG3Rm4Omu7YnqK/vn9SupB/rdZcKbtdB+1YRwCQiFek9r1SC/OjrtddNDk4c3keXzdCxIVK5Xp+GRw=
  app: glacial-coast-3420
  run:
    - "heroku config:set RAILS_APP_VERSION=$(git rev-parse --short master)"
    - "heroku config:set SECRET_KEY_BASE=$(rake secret)"
    - "rake db:migrate"
  on:
    repo: deiga/ratebeer
env:
  global:
  - secure: LyIqsLUDgA1bMuL5K4+qTw1kuyMmjD3Y0D4WQaFMLnHjiahweXOz48P2p9ICaNlTkbQTSKeXmI48IGZE3XFj3w6bHlzbv5B0LUni2/wMmu9ORArSgBq6SpE2ehsH2+ls4L5x46Wrm+qCf7DzhbR0CjQW5Yp6uLKYrN/UYgG5jWo=
  - secure: Ly/EAOPIJz6bPVhx+bnHasQi8ZHF6lhtnbJE0SzPStFWIRCuFRWIyyLHMp8L+DqYNBMKAt1eHc17E3iCKhUP5uJqZuSgzhAZ0zkH9pRMoRnZNJRqb2XeC96Z0MyFElL3b3ul66vSCOYLZgJorRQEiV13PVkLH9stl1X89Y4Vutk=
